### ISSUE TITLE
이미 등록된 항목에 대한 id 표시

### ISSUE THREAD

**Issue by freekering** [ridi/simple-service-status#54]
리스트나 수정 화면에서 id를 확인할 수 있으면 좋을 것 같습니다.

**Comment by kyungmi** [comment]
id가 순번이 아니라서 보여주는게 좋을지 모르겠네요.
지금은 MongoDB에서 자동으로 발급해주는 ObjectId를 그대로 쓰고 있어요.

**Comment by freekering** [comment]
API 호출 시 나오는 항목하고 매칭시킬 수 있는 방법이 딱히 없는 것 같아서요. 수정 화면 URL이 따로 있는것도 아니고..
