### ISSUE TITLE
프로젝트명/organization 변경에 따른 후속조치

### ISSUE THREAD

**Issue by freekering** [ridi/simple-service-status#59]
- [x] README
- [x] Travis CI
- [x] npm
- [x] Scrutinizer-CI

**Comment by namenu** [comment]
마이볼 -> Scrutinizer-CI

**Comment by kyungmi** [comment]
npm에 배포했습니다. https://www.npmjs.com/package/simple-service-status

**Comment by kyungmi** [comment]
Scrutinizer-CI 연결했어요
