### ISSUE TITLE
리디스토리 서비스 점검 서버 적용 관련 요구사항

### ISSUE THREAD

**Issue by antiline** [ridi/simple-service-status#65]
- 리디스토리는 서비스 점검시 일시적으로 요청을 받을 서비스로 사용하려고함
- 사용중인 도메인은 www.ridistory.com, api.ridistory.com, app.ridistory.com, cp.ridistory.com, admin.ridistory.com 으로 총 5개임
- 하나의 서버에서 위 모든 도메인들을 서비스 할 수 있어야 함
- api.ridistory.com 만 json 응답이고 나머지는 html 응답임
- 응답 html 을 고정하는것이 아니라 사이트별 수정 할 수 있어야함
- 응답시 status code 를 200이 아니라 다른 값으로 변경 가능해야 함
- json 응답 구조를 변경할 수 있으면 좋을것 같음
- 도커로 포장되어 있으면 좋을것 같음
- 10월 23일 사용 예정 : 테스트 위해 10월 13일 정도에는 가능했으면 함

**Comment by antiline** [comment]
@kgwangrae 위 요구사항 관련해서 확인 부탁드립니다.

**Comment by freekering** [comment]
@antiline 이 프로젝트는 @kyungmi 님한테 말씀하시면 됩니다.
그런데 리디북스 앱과 리디스토리 앱의 차이 때문에 요구사항이 많이 차이가 나는것 같습니다.
리디북스 앱은 점검(혹은 장애) 중이라도 앱을 잘못 업데이트해서 장애가 발생한 것이 아닌 이상 이미 다운받아 놓은 책을 보는 데는 아무 지장이 없어서 그냥 한번 요청해서 결과를 받아와서 팝업을 보여주는 정도의 용도로만 활용하고 있습니다.
리디스토리는 그렇지 않고 아마 대체적으로 전체 서비스 이용이 불가능하기 때문에 사용중인 모든 end point에 대해서 점검중이라는 표시를 렌더링하고자 하시는 거 같은데 그러면 이런 방식보다는 오히려 현재 리디북스 서점에서 사용하는 방식 (DNS 변경을 통해 별도의 점검 중 페이지를 렌더링 하는)이 요구사항에 더 부합할 것 같습니다.
결론적으로 요구사항 자체가 애초에 이 프로젝트에서 하고자 했던 방향과는 다른 것 같습니다.

**Comment by kyungmi** [comment]
@antiline 
제가 아까 좀 잘못 이해한 것 같은데, 위에 알려주신 해당 도메인으로 이동했을 때 장애 페이지(html)를 렌더링 해야 한다는 말씀이신거죠?
simple-service-status 는 독립적인 서버로 구현되어 있어서, 스토리에서 운영하고 계신 서버 접근 방식에 관여할 수는 없고요. simple-service-status 서버에 직접 요청을 해서 장애 상황을 알아내야 하거든요.
리디 스토리에서 simple-service-status에 API 요청을 해서 장애 상황을 알아낸 후 직접 렌더링을 하는 방식이 아니면 좀 어려울 것 같아요.

**Comment by namenu** [comment]
추가 요구사항이 엄청 많네요 ㅎㅎㅎ

우선 요구사항의 방향성이 크게 다른 문제가 있고, 이 프로젝트는 뷰어팀에서 주력으로 관리하는 것이 아니기 때문에 이 정도의 대응을 하기가 어렵습니다. (정 필요하다면 PR을..)

이거는 '서버가 죽었을때 앱이 먹통이 되지 않고 긴급 공지를 하기 위함'이 주된 목적입니다.
이 사용성 이상이 필요하면 다른 방안을 찾아보아야 할 것 같습니다.

**Comment by antiline** [comment]
원래 개발된 목적이 저희가 사용하려는 목적에 부족함이 있어 경미님꼐 관련된 사항에 대해 문의를 드렸습니다.
서로 정리가 잘 안되는것 같아서 이슈로 정리해봤고, 역시 우려했던것 처럼 방향이 맞지 않아 따로 개발을 해야 할것 같습니다.

PR을하기에도 해당 서버 목적에 맞지 않기에 간단히 새로 개발하겠습니다.
